### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by nidhog** [pontusgranath/svt-apl#15]
The exception handling in this line seems a little off: https://github.com/pontusgranath/svt-apl/blob/c3df678de55f1b7ba876960cbfe7e6be9f89ae7f/django_project/dist_search/views.py#L67

This is basically saying, if there's any `ValueError` then set the search to `Agenda` and search again. While it may work, if the error is thrown for another reason the search result for Agenda will be given. You should also consider that this dataset only contains 100 most popular titles, if all titles are added it's very likely a new title will give the same error, in which case this will display Agenda's search result.

**Comment by nidhog** [comment]
The same applies to `amount_of_titles`

**Comment by felixxlll** [comment]
This should be fixed now. We made an error page that gets displayed if you type something invalid in the search-bar. We decided to keep `amount_of_titles` 5 as we think that works fine as it is. We did however change the placeholder text to 5 to make it clearer.
